#!/bin/bash
# Source: add
# adds : to front of each line of several files & concatenates
# result into bigfile

for  file  in  fn?                 #<--  fn1, fn2 fny  etc
do
     cat  $file |  \
     while  read line              #<--  reads a line of stdin
                                   #     into  var  line
     do
          echo  ":$line"
     done | cat >>  big-file       #%%need >> or last file will clobber
done
echo "after while loop value of line is $line"  #null 
exit 0
