#!/bin/bash
#source cla
#program to print out all command line args one at a time
for i 
do
    echo "$i"   #quotes preserve whitespace withing $i
#   echo  $i    
done       # | wc -l   # if wanted a count of clas instead
exit 0

