#!/bin/bash
#Source: countod1
#like countod except the read is the while condition

typeset -i  ordfile=0
typeset -i  dirfile=0

echo  Enter a file name or  END to quit
while  read filenam
do
     if  [ "$filenam" = "END" -o "$filenam" = "end" ]
     then
          break
     fi
     if   [ -f  "$filenam" ]
     then
          ordfile=ordfile+1
     elif  [ -d "$filenam" ]
     then
          dirfile=dirfile+1
     fi
     echo  Enter a file name or  END to quit     
done
echo -e "The number of ordinary files:\t  $ordfile"
echo -e "The number of directories:\t  $dirfile"
exit 0
