#!/bin/bash
#Source: countodFile2
# like countod except input read from a file which
# is supplied as a command line argument ($1)
# File countodInput is one such input file, so can run
# ./countodFile2 countodInput

typeset -i  ordfile=0
typeset -i  dirfile=0

while  read filenam
do
     if  [ "$filenam" = "END" -o "$filenam" = "end" ]
     then
          break
     fi
     if   [ -f  "$filenam" ]
     then
          ordfile=ordfile+1
     elif  [ -d "$filenam" ]
     then
          dirfile=dirfile+1
     fi
done < $1
echo -e "The number of ordinary files:\t  $ordfile"
echo -e "The number of directories:\t  $dirfile"
exit 0
