#!/bin/bash
#source ff
if [ "`grep $1 file1`" ]
then
   echo string $1 is contained in file file1
else
   echo string $1 is not contained in file file1
fi
#works because grep prints null to stdout if not found and
#some string if it is found
#what happens if run this with $1 not set?
