#!/bin/bash
#source ff

if [ -z "$1" ]
then
   echo "Usage: $0 string"
   exit 1
fi


if [ "`grep $1 f1`" ]
then
   echo string $1 is contained in file f1
else
   echo string $1 is not contained in file f1
fi
exit 0
#works because grep prints null to stdout if not found and
#some string if it is found
#what happens if run this with $1 not set?
