#!/bin/bash
#Source filedir
#tells if each item in current dir is file or dir
#needs to check $1 exists etc....

unalias ls 2>/dev/null

 for  file  in `ls $1`
 do
      if  [  -f  ${1}/$file ]           # or if test -f $file
      then
           echo  "${1}/$file  is  file"
      else
           if  [  -d  ${1}/$file  ]     # or if test -d $file
           then
                echo  "  ${1}/$file  is  dir. "
           fi
      fi
done
exit 0

