#!/bin/bash
#Source:  findtrunc1     truncates input to  8  characters and
#looks it up in file   gfile
# a msg is printed to indicate if found/not found

echo  "$1" | cut  -c1-8 >tmp
read trunc <tmp
if  [ "`grep  $trunc  gfile`" ]
then  echo  Found
else   echo   not  found
fi
test -e tmp && rm tmp   #rm it only if it exists so no error msg prntd


