#!/bin/bash
#source: showSource
#shell program to list all java and c files in current directory
echo -n "Current directory is: "
pwd
echo "C files are:"
ls *.c
echo "Java files are:"
ls *.jav
exit 0
