#!/bin/bash
#source: showSource1
#shell program  to list all source java and c files in current directory
echo -n "Current directory is:" ;pwd
echo "C files are:"
ls *.c
echo "Java files are:"
ls *.jav
