#!/bin/bash
#Source: to46
#Usage:  to46 4<infile 6>outfile
# shell pgm reads one line of file assd. with  FD4 and
# writes line twice to stdout & once to file assd.  FD6
first=`head -1 <&4`
echo $first  >&1
echo $first  >&6
echo $first
exit 0

