#!/bin/bash
#Source:  findtrunc      truncates $1 to  8  characters and
#searches for it in file   gfile
# a msg is printed to indicate if found/not found

trunc=`echo  "$1" | cut  -c1-8`
if  [ "`grep  $trunc  gfile`" ]
then  echo  Found
else   echo   not found
fi
