#!/bin/bash
#Source:  findtrunc      truncates input to  8  characters &
#looks it up in file   gfile
# a msg is printed to indicate if found/not found
#use first method on linux, second on unix (why? "feature" in linux bash
#that runs each part of a pipe in a different process, so vars do not
#get into the process running the "read"
#third method always works, but no help if want to use read to separate
#by whitespace
#first method:
#echo  "$1" | cut  -c1-8 >tmp
#read trunc <tmp
#second method:
echo  "$1" | cut  -c1-8 |  read trunc
#third method
# trunc=`echo  "$1" | cut  -c1-8`
if  [ "`grep  $trunc  gfile`" ]
then  echo  Found
else   echo   not  found
fi
test -e tmp && rm tmp   #rm it only if it exists so no error msg prntd


